apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pyhello
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: dev
            server: https://kubernetes.default.svc
          - namespace: prod
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{namespace}}-pyhello'
    spec:
      project: default
      source:
        #repoURL: https://github.com/rvega-clearroute/pyhello.git
        repoURL: oci://europe-west2-docker.pkg.dev/valid-oven-400113/helm-repository
        targetRevision: master
        path: Helm/{{namespace}}/pyhello
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

