apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pyhello
spec:
  generators:
    - list:
        elements:
          - namespace: dev
            server: https://kubernetes.default.svc
          - namespace: prod
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{namespace}}-pyhello'
    spec:
      project: default
      source:
        repoURL: https://github.com/rvega-clearroute/pyhello.git
        targetRevision: HEAD
        path: Helm/pyhello/{{namespace}}-values.yaml
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true