apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyhello
  namespace: pyhello
spec:
  project: default
  source:
    repoURL: https://github.com/rvega-clearroute/pyhello.git
    targetRevision: HEAD
    path: Helm/pyhello
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true # revert manual changes done using kubectl
      prune: true    # deleting configuration after the file is renamed or removed
