apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pyhello
spec:
  generators:
    - list:
        elements:
          - namespace: dev
            url: https://kubernetes.default.svc
          - namespace: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-pyhello'
    spec:
      project: default
      source:
        path: Helm/pyhello
        repoURL: https://github.com/rvega-clearroute/pyhello.git
        targetRevision: HEAD
        helm:
          releaseName: pyhello
          valueFiles:
            - values.yaml
            - values-{{"{{"}}namespace{{"}}"}}.yaml
      destination:
        server: '{{"{{"}}url{{"}}"}}'
        namespace: '{{"{{"}}namespace{{"}}"}}'